
-- Q1
SELECT ENAME FROM EMP
WHERE ENAME LIKE '_i%';

-- Q2
SELECT COUNT(DISTINCT MGR) FROM EMP;

-- Q3
SELECT MAX(SAL) AS MAXIMUM,
	   MIN(SAL) AS MINIMUM,
	   SUM(SAL) AS TOTAL,
	   AVG(SAL) AS AVERAGE
FROM EMP;

-- Q4
SELECT JOB,
       MAX(SAL) AS MAXIMUM,
	   MIN(SAL) AS MINIMUM,
	   SUM(SAL) AS TOTAL,
	   AVG(SAL) AS AVERAGE
FROM EMP GROUP BY JOB;

-- Q5
SELECT COUNT(DISTINCT MGR) AS "NUMBER OF MANAGERS" FROM EMP;

-- Q6
SELECT * FROM EMP
WHERE HIREDATE>'01-Jan-1980';

-- Q7 ##
SELECT ENAME,MAX(SAL) FROM EMP
GROUP BY JOB
HAVING JOB LIKE 'Salesman';




-- Q8 ##
SELECT ENAME,MIN(SAL) FROM EMP
GROUP BY JOB
HAVING JOB LIKE 'Clerk';

-- Q9
SELECT ENAME FROM EMP
WHERE SAL>(
			SELECT SAL FROM EMP
			WHERE ENAME LIKE 'Turner');
			
-- Q10
SELECT DNAME FROM EMP E,DEPT D
WHERE E.DNO=D.DNO
AND ENAME LIKE 'Ford';

-- Q11
SELECT DNAME FROM EMP E,DEPT D
WHERE E.DNO=D.DNO
AND SAL=(SELECT MAX(SAL) FROM EMP);

-- 1ST Q == WHO ARE NOT MANAGERS
SELECT * FROM EMP
WHERE ENAME NOT IN (
					SELECT M.ENAME FROM EMP E,EMP M
					WHERE E.MGR=M.EMPNO);




SELECT * FROM EMP E,EMP M
WHERE E.MGR=M.EMPNO;

-- DUAL ASSIGNMENT

-- Q1
SELECT 2*5+9 FROM DUAL;

-- Q2
SELECT CURRENT_TIMESTAMP FROM DUAL;

-- Q3
SELECT UPPER('sample text') FROM DUAL;

-- Q4
SELECT SUBSTR('sample text',1,5) FROM DUAL;

--Q5
SELECT CURRENT_DATE-1 AS YESTERDAY,
	   CURRENT_DATE AS TODAY,
	   CURRENT_DATE+1 AS TOMORROW
	   FROM DUAL;
	   
--Q6
SELECT EXTRACT(MONTH FROM SYSDATE), EXTRACT(YEAR FROM SYSDATE) FROM DUAL;

-- Q7
SELECT SIN(90),COS(47),TAN(85),ACOS(.12),TANH(57) FROM DUAL;

-- Q8
SELECT DBMS_RANDOM.RANDOM,CEIL(22.453),FLOOR(55.36),ABS(-67) FROM DUAL;

-- Q9
SELECT SQRT(5) FROM DUAL;

-- Q10
SELECT LOWER('IVAN BAYROSS') FROM DUAL;

-- Q11
SELECT UPPER('IVAN BAYROSS') FROM DUAL;

-- Q12
SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY') FROM DUAL;

-- Q13
SELECT ABS(MONTHS_BETWEEN('02-JAN-01','02-JUL-01')) FROM DUAL;

-- Q14
SELECT ADD_MONTHS(SYSDATE,5) FROM DUAL;

-- Q15
SELECT ROUND(15.19,1) FROM DUAL;