
CREATE TABLE SAILORS(
					S_ID VARCHAR2(5) PRIMARY KEY,
					S_NAME VARCHAR2(50),
					RATING NUMBER(2,1) CHECK(RATING <= 5.0 AND RATING >= 0.0),
					AGE NUMBER(3));
					
CREATE TABLE BOATS(
				B_ID VARCHAR2(5) PRIMARY KEY,
				B_NAME VARCHAR2(50),
				COLOR VARCHAR2(10));
				
CREATE TABLE RESERVES(
					S_ID VARCHAR2(5) REFERENCES SAILORS(S_ID) ON DELETE CASCADE,
					B_ID VARCHAR2(5) REFERENCES BOATS(B_ID),
					DAY VARCHAR2(20));
					

INSERT ALL
INTO SAILORS VALUES('10','John',4.2,44)
INTO SAILORS VALUES('11','Dave',3.9,54)
INTO SAILORS VALUES('12','Jim',4,28)
INTO SAILORS VALUES('13','Mike',3.6,66)
INTO SAILORS VALUES('14','Bill',4.9,31)
INTO SAILORS VALUES('15','Nathan',4.3,32)
INTO SAILORS VALUES('16','Ryan',4,57)
INTO SAILORS VALUES('17','Andy',3,61)
INTO SAILORS VALUES('18','David',2.9,64)
INTO SAILORS VALUES('19','Tarun',4.1,25)
SELECT * FROM DUAL;


INSERT ALL
INTO BOATS VALUES('300','Tigershark','Red')
INTO BOATS VALUES('301','SS Minnow','Red')
INTO BOATS VALUES('302','Dawn Patrol','Green')
INTO BOATS VALUES('303','Black Pearl','Black')
INTO BOATS VALUES('304','Devil Wind','Blue')
INTO BOATS VALUES('305','SS Riptide','Green')
INTO BOATS VALUES('306','Wave Rider','Red')
INTO BOATS VALUES('307','Second Wind','Yellow')
SELECT * FROM DUAL;

INSERT ALL 
INTO RESERVES VALUES('11','303','Monday')
INTO RESERVES VALUES('14','301','Tuesday')
INTO RESERVES VALUES('16','303','Friday')
INTO RESERVES VALUES('15','302','Monday')
INTO RESERVES VALUES('18','303','Sunday')
INTO RESERVES VALUES('12','300','Monday')
INTO RESERVES VALUES('19','307','Wednesday')
INTO RESERVES VALUES('13','303','Tuesday')
INTO RESERVES VALUES('13','307','Monday')
INTO RESERVES VALUES('19','305','Saturday')
INTO RESERVES VALUES('17','306','Friday')
SELECT * FROM DUAL;

SELECT COLOR FROM SAILORS,RESERVES,BOATS 
WHERE SAILORS.S_ID = RESERVES.S_ID 
AND RESERVES.B_ID = BOATS.B_ID
AND SAILORS.S_NAME LIKE 'Tarun';

SELECT SAILORS.S_ID,SAILORS.S_NAME FROM SAILORS,RESERVES,BOATS 
WHERE SAILORS.S_ID = RESERVES.S_ID 
AND RESERVES.B_ID = BOATS.B_ID
AND RESERVES.DAY LIKE 'Monday';

SELECT B_ID,B_NAME FROM BOATS
WHERE COLOR IN ('Red','Green');

DELETE FROM SAILORS 
WHERE AGE > 60;

CREATE TABLE TEACHER(
					TID VARCHAR2(5) PRIMARY KEY,
					NAME VARCHAR2(10),
					DEPT VARCHAR2(5));
					
CREATE TABLE SUBJECT(
					SUBNO VARCHAR2(5) PRIMARY KEY,
					SUBTITLE VARCHAR2(50));
					
					
CREATE TABLE TAUGHTBY(
					TID VARCHAR2(5) REFERENCES TEACHER(TID),
					SUBNO VARCHAR2(5) REFERENCES SUBJECT(SUBNO));
					
					
INSERT ALL
INTO TEACHER VALUES('40','A.H','CSE')
INTO TEACHER VALUES('41','D.C','CSE')
INTO TEACHER VALUES('42','S.Da','HR')
INTO TEACHER VALUES('43','S.G','PHYS')
INTO TEACHER VALUES('44','S.S.G','ECE')
INTO TEACHER VALUES('45','R.N.D','ECE')
INTO TEACHER VALUES('46','G.Y','CSE')
INTO TEACHER VALUES('47','So.M','PHYS')
INTO TEACHER VALUES('48','S.S.K','CSE')
SELECT * FROM DUAL;

INSERT ALL
INTO SUBJECT VALUES('20','Thermodynamics')
INTO SUBJECT VALUES('21','DBMS')
INTO SUBJECT VALUES('22','Signals & Systems')
INTO SUBJECT VALUES('23','Human Resource & Development')
SELECT * FROM DUAL;

INSERT ALL
INTO TAUGHTBY VALUES('43','20')
INTO TAUGHTBY VALUES('47','20')
INTO TAUGHTBY VALUES('41','21')
INTO TAUGHTBY VALUES('42','23')
SELECT * FROM DUAL;

SELECT NAME FROM TEACHER,TAUGHTBY,SUBJECT 
WHERE TEACHER.TID = TAUGHTBY.TID
AND TAUGHTBY.SUBNO = SUBJECT.SUBNO
AND TEACHER.DEPT LIKE 'PHYS'
AND SUBJECT.SUBTITLE LIKE 'Thermodynamics';

UPDATE SUBJECT
SET SUBTITLE = 'RDBMS'
WHERE SUBTITLE = 'DBMS';

CREATE TABLE STUDENT(
					ROLLNO VARCHAR2(3),
					SNAME VARCHAR2(20),
					CITY VARCHAR2(10));
					
INSERT ALL
INTO STUDENT VALUES(24,'Rohit Roy','Kolkata')
INTO STUDENT VALUES(25,'Ankan Sen','Kolkata')
INTO STUDENT VALUES(20,'Arpan Das','Kolkata')
INTO STUDENT VALUES(29,'Nandan Singh','Bihar')
INTO STUDENT VALUES(18,'Debjit Shah','Bihar')
INTO STUDENT VALUES(15,'S.P Singh','UP')
INTO STUDENT VALUES(12,'Anirban Mondal','Kolkata')
SELECT * FROM DUAL;

SELECT * FROM STUDENT
WHERE CITY LIKE 'Kolkata'
AND ROLLNO BETWEEN 20 AND 25;		

SELECT * FROM STUDENT 
WHERE CITY LIKE 'Kolkata'
ORDER BY ROLLNO DESC;		
					
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'SALES_ORDER';